### ISSUE TITLE
unrecognized command: "Skeletonized(2D\3D)"

### ISSUE THREAD

**Issue by zhang14725804** [ScienceToolkit/MiNA#2]
![_20171119213100](https://user-images.githubusercontent.com/15354910/32991150-f822bbd4-cd70-11e7-817d-bb1d068dc89d.jpg)

when i click "Analyze",alert this mistakes

**Comment by ScienceToolkit** [comment]
Do you have [Skeletonize 2D/3D](https://imagej.net/Skeletonize3D) and [Analyze Skeleton 2D/3D](https://imagej.net/AnalyzeSkeleton) plugins installed? 

The easiest way to ensure everything needed is there is to use the [FIJI](https://fiji.sc/) distribution of ImageJ. It is packaged with all of the plugins and tools used in the macro. 

__PLEASE NOTE__: _MiNA 2.0.0 is still very much in the development phase and has not been thoroughly tested yet. I can't guarantee it is all working well. If you find more issues, submitting them as you did this one is very helpful!_

**Comment by zhang14725804** [comment]
thank you!

**Comment by zhang14725804** [comment]
![0183705](https://user-images.githubusercontent.com/15354910/33014377-13cf6eca-ce22-11e7-96f2-48ccb3f4f7c5.png)
how can i get image like this "box-image",by using other tools?

**Comment by ScienceToolkit** [comment]
No problem! :)

**Comment by dtdy1841** [comment]
Why does a mitochondrial figure can get three or four sets of parameters？

**Comment by ScienceToolkit** [comment]
I am not sure I follow. Can you show me an example of what you mean by mitochondrial figure?

**Comment by dtdy1841** [comment]
I already got it.MINA can save the result of the previous test  automatically .Thank you for your reply.

**Comment by ScienceToolkit** [comment]
Ok, great! I will close this issue then.
