### ISSUE TITLE
Analysis of MiNA in myotube cells

### ISSUE THREAD

**Issue by kazuma72521** [ScienceToolkit/MiNA#7]
Hello.
I am a Japanese college student and I am conducting research related to mitochondrial morphology in muscle cell(C2C12).

I am very grateful that I have used Mina that you developed very usefully.

I am planning to use Mina in myotube cells in this study, but is MiNA appropriate to use it?
If you do not mind, I would like to ask your opinion

Specifically, I am planning an experimental design to compare mitochondrial morphology of the control group (myotube cells) with drug administration group (muscle atrophic cell) by MiNA.

I would be pleased if you could reply.

**Comment by ScienceToolkit** [comment]
Hello,

In short, I am not able to tell you that. As is stated in the processing pipeline section on the [project wiki page](https://imagej.net/index.php?title=MiNA_-_Mitochondrial_Network_Analysis&action=submit#Processing_Pipeline_and_Usage):

>It is mandatory that users ensure the morphological skeleton can be accurately generated for their system of interest. The analysis tool is typically not suitable for extremely clumped mitochondria, poorly resolved images, or images with low contrast. The overlay (or 3D render) is intended as a means to assess whether the model from which the parameters are generated will be meaningful or not.

In cells or tissues where mitochondria are very dense, it is unlikely that the mitochondria would be sufficiently resolved to allow for analysis of fluorescence microscopy images. In these cases it may not even be possible to examine mitochondrial morphology without super-resolution or electron microscopy techniques. It is the responsibility of the user to determine whether the fit of the skeleton is a visually accurate representation and whether or not fluorescence microscopy is a suitable tool for your sample.

Cheers,
ScienceToolkit

**Comment by kazuma72521** [comment]
Thank you very much for answering the question.
 I understood what you are saying. 

Finally thank you very much for you developing this plugin.
